import { NavItem, PageConfig, Category } from '../types';

export const navigationConfig: NavItem[] = [
  {
    slug: '/',
    title: 'Dashboard',
    description: 'Overview of all resources',
    icon: 'LayoutDashboard',
    order: 0,
    group: 'main',
  },
  {
    slug: '/tools',
    title: 'AI Tools',
    description: 'Curated AI development tools',
    icon: 'Wrench',
    order: 1,
    group: 'resources',
  },
  {
    slug: '/documentation',
    title: 'Documentation',
    description: 'AI documentation and references',
    icon: 'BookOpen',
    order: 2,
    group: 'resources',
  },
  {
    slug: '/claude-code',
    title: 'Claude Code',
    description: 'Claude Code resources and guides',
    icon: 'Terminal',
    order: 3,
    group: 'resources',
  },
  {
    slug: '/skills',
    title: 'Skills',
    description: 'AI agent skills and SKILL.md resources',
    icon: 'Brain',
    order: 4,
    group: 'resources',
  },
  {
    slug: '/prompts',
    title: 'Prompt Templates',
    description: 'Ready-to-use prompt templates',
    icon: 'MessageSquare',
    order: 5,
    group: 'templates',
  },
  {
    slug: '/markdown',
    title: 'Markdown Templates',
    description: 'Documentation and project templates',
    icon: 'FileText',
    order: 6,
    group: 'templates',
  },
  {
    slug: '/developer',
    title: 'Developer Resources',
    description: 'Tools and references for developers',
    icon: 'Code',
    order: 7,
    group: 'resources',
  },
  {
    slug: '/design',
    title: 'Design Resources',
    description: 'UI/UX and design references',
    icon: 'Palette',
    order: 8,
    group: 'resources',
  },
  {
    slug: '/websites',
    title: 'Useful Websites',
    description: 'External AI and dev resources',
    icon: 'Globe',
    order: 9,
    group: 'resources',
  },
  {
    slug: '/about',
    title: 'About',
    description: 'About AiTools and author',
    icon: 'Info',
    order: 100,
    group: 'meta',
  },
];

export const pageConfigs: PageConfig[] = navigationConfig.map((item) => ({
  slug: item.slug,
  title: item.title,
  description: item.description,
  icon: item.icon,
  order: item.order,
  visible: item.visible ?? true,
  group: item.group,
}));

export const categories: Category[] = [
  {
    id: 'ai-tools',
    name: 'AI Tools',
    description: 'AI development and productivity tools',
    icon: 'Wrench',
    slug: 'tools',
    order: 1,
    visible: true,
  },
  {
    id: 'documentation',
    name: 'Documentation',
    description: 'Official docs and references',
    icon: 'BookOpen',
    slug: 'documentation',
    order: 2,
    visible: true,
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Claude Code specific resources',
    icon: 'Terminal',
    slug: 'claude-code',
    order: 3,
    visible: true,
  },
  {
    id: 'skills',
    name: 'Skills',
    description: 'AI agent skills (SKILL.md)',
    icon: 'Brain',
    slug: 'skills',
    order: 4,
    visible: true,
  },
  {
    id: 'prompts',
    name: 'Prompt Templates',
    description: 'Reusable prompt templates',
    icon: 'MessageSquare',
    slug: 'prompts',
    order: 5,
    visible: true,
  },
  {
    id: 'markdown',
    name: 'Markdown Templates',
    description: 'Documentation and project templates',
    icon: 'FileText',
    slug: 'markdown',
    order: 6,
    visible: true,
  },
  {
    id: 'developer',
    name: 'Developer Resources',
    description: 'General developer tools and references',
    icon: 'Code',
    slug: 'developer',
    order: 7,
    visible: true,
  },
  {
    id: 'design',
    name: 'Design Resources',
    description: 'UI/UX design references and tools',
    icon: 'Palette',
    slug: 'design',
    order: 8,
    visible: true,
  },
  {
    id: 'websites',
    name: 'Useful Websites',
    description: 'External AI and dev websites',
    icon: 'Globe',
    slug: 'websites',
    order: 9,
    visible: true,
  },
];
